remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Kathryn Kong's Profile
description: Welcome to my academic journey pursuing a PhD in Texts and Technology at the University of Central Florida!
